// leetcode link -> https://leetcode.com/problems/find-the-first-player-to-win-k-games-in-a-row/description/

class Solution {
    public int findWinningPlayer(int[] skills, int k) {
        if (k >= skills.length) {
            int max = skills[0];
            int maxIndex = 0;
            for (int i = 1; i < skills.length; i++) {
                if (max < skills[i]) {
                    max = skills[i];
                    maxIndex = i;
                }
            }
            return maxIndex;
        }

        else {
            int max = skills[0];
            int maxIndex = 0;
            int count = 0;
            for (int i = 0; i < skills.length - 1; i++) {
                if (max > skills[i + 1]) {
                    count++;
                }
                else {
                    max = skills[i + 1];
                    maxIndex = i + 1;
                    count = 1;
                }
                if (count == k) {
                    break;
                }
            }
            return maxIndex;
        }
    }
}
